## Append samples you want in your CSV to this file as resources ##
# Dev note: renaming these files is not allowed as operator-sdk later uses them
# to generate proper CSV documents
resources:
  - atlas_v1_atlasdeployment.yaml
  - atlas_v1_atlasproject.yaml
  - atlas_v1_atlasdatabaseuser.yaml
  - atlas_v1_atlasbackuppolicy.yaml
  - atlas_v1_atlasbackupschedule.yaml
  - dbaas_v1alpha1_atlasconnection.yaml
  - dbaas_v1alpha1_atlasinventory.yaml
  - dbaas_v1alpha1_atlasinstance.yaml
  - dbaas_v1alpha2_atlasconnection.yaml
  - dbaas_v1alpha2_atlasinventory.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
